<?php

/**
 * BaseAdminUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $AdminUserGroup
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method Doctrine_Collection getAdminUserGroup() Returns the current record's "AdminUserGroup" collection
 * @method AdminUserGroup      setName()           Sets the current record's "name" value
 * @method AdminUserGroup      setAdminUserGroup() Sets the current record's "AdminUserGroup" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAdminUserGroup extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_user_group');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as AdminUserGroup', array(
             'local' => 'id',
             'foreign' => 'admin_user_group_id'));
    }
}