<?php

/**
 * BaseNewsGroupVsStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $structure_id
 * @property NewsGroup $NewsGroup
 * @property Structure $Structure
 * 
 * @method integer              getGroupId()      Returns the current record's "group_id" value
 * @method integer              getStructureId()  Returns the current record's "structure_id" value
 * @method NewsGroup            getNewsGroup()    Returns the current record's "NewsGroup" value
 * @method Structure            getStructure()    Returns the current record's "Structure" value
 * @method NewsGroupVsStructure setGroupId()      Sets the current record's "group_id" value
 * @method NewsGroupVsStructure setStructureId()  Sets the current record's "structure_id" value
 * @method NewsGroupVsStructure setNewsGroup()    Sets the current record's "NewsGroup" value
 * @method NewsGroupVsStructure setStructure()    Sets the current record's "Structure" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNewsGroupVsStructure extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_group_vs_structure');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NewsGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}