<?php

/**
 * BaseNewsGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $type
 * @property integer $pri
 * @property boolean $is_active
 * @property integer $link_to_struct
 * @property Doctrine_Collection $GroupNews
 * @property Doctrine_Collection $StructureNewsGroup
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getType()               Returns the current record's "type" value
 * @method integer             getPri()                Returns the current record's "pri" value
 * @method boolean             getIsActive()           Returns the current record's "is_active" value
 * @method integer             getLinkToStruct()       Returns the current record's "link_to_struct" value
 * @method Doctrine_Collection getGroupNews()          Returns the current record's "GroupNews" collection
 * @method Doctrine_Collection getStructureNewsGroup() Returns the current record's "StructureNewsGroup" collection
 * @method NewsGroup           setName()               Sets the current record's "name" value
 * @method NewsGroup           setType()               Sets the current record's "type" value
 * @method NewsGroup           setPri()                Sets the current record's "pri" value
 * @method NewsGroup           setIsActive()           Sets the current record's "is_active" value
 * @method NewsGroup           setLinkToStruct()       Sets the current record's "link_to_struct" value
 * @method NewsGroup           setGroupNews()          Sets the current record's "GroupNews" collection
 * @method NewsGroup           setStructureNewsGroup() Sets the current record's "StructureNewsGroup" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNewsGroup extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'default',
             'length' => '255',
             ));
        $this->hasColumn('pri', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('link_to_struct', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('NewItem as GroupNews', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('NewsGroupVsStructure as StructureNewsGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));
    }
}