<?php

/**
 * BaseFrontendModule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $action
 * @property Doctrine_Collection $BackendModules
 * @property Doctrine_Collection $Placeholder
 * @property Doctrine_Collection $FrontendModule
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getAction()         Returns the current record's "action" value
 * @method Doctrine_Collection getBackendModules() Returns the current record's "BackendModules" collection
 * @method Doctrine_Collection getPlaceholder()    Returns the current record's "Placeholder" collection
 * @method Doctrine_Collection getFrontendModule() Returns the current record's "FrontendModule" collection
 * @method FrontendModule      setName()           Sets the current record's "name" value
 * @method FrontendModule      setAction()         Sets the current record's "action" value
 * @method FrontendModule      setBackendModules() Sets the current record's "BackendModules" collection
 * @method FrontendModule      setPlaceholder()    Sets the current record's "Placeholder" collection
 * @method FrontendModule      setFrontendModule() Sets the current record's "FrontendModule" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFrontendModule extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('frontend_module');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('action', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'render',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BackendModule as BackendModules', array(
             'local' => 'id',
             'foreign' => 'frontend_module_id'));

        $this->hasMany('Placeholder', array(
             'local' => 'id',
             'foreign' => 'frontend_module_id'));

        $this->hasMany('PlaceholdersVsModules as FrontendModule', array(
             'local' => 'id',
             'foreign' => 'frontend_module_id'));
    }
}