<?php

/**
 * BaseProductGroupVsParameterGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $prodgroup_id
 * @property integer $paramgroup_id
 * @property ProductGroup $ProductGroup
 * @property ParameterGroup $ParameterGroup
 * 
 * @method integer                      getProdgroupId()    Returns the current record's "prodgroup_id" value
 * @method integer                      getParamgroupId()   Returns the current record's "paramgroup_id" value
 * @method ProductGroup                 getProductGroup()   Returns the current record's "ProductGroup" value
 * @method ParameterGroup               getParameterGroup() Returns the current record's "ParameterGroup" value
 * @method ProductGroupVsParameterGroup setProdgroupId()    Sets the current record's "prodgroup_id" value
 * @method ProductGroupVsParameterGroup setParamgroupId()   Sets the current record's "paramgroup_id" value
 * @method ProductGroupVsParameterGroup setProductGroup()   Sets the current record's "ProductGroup" value
 * @method ProductGroupVsParameterGroup setParameterGroup() Sets the current record's "ParameterGroup" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductGroupVsParameterGroup extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_group_vs_parameter_group');
        $this->hasColumn('prodgroup_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('paramgroup_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductGroup', array(
             'local' => 'prodgroup_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('ParameterGroup', array(
             'local' => 'paramgroup_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}