<?php

/**
 * BasePlaceholder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $frontend_module_id
 * @property integer $structure_id
 * @property string $action
 * @property string $name
 * @property integer $pri
 * @property FrontendModule $FrontendModule
 * @property Structure $Structure
 * 
 * @method integer        getFrontendModuleId()   Returns the current record's "frontend_module_id" value
 * @method integer        getStructureId()        Returns the current record's "structure_id" value
 * @method string         getAction()             Returns the current record's "action" value
 * @method string         getName()               Returns the current record's "name" value
 * @method integer        getPri()                Returns the current record's "pri" value
 * @method FrontendModule getFrontendModule()     Returns the current record's "FrontendModule" value
 * @method Structure      getStructure()          Returns the current record's "Structure" value
 * @method Placeholder    setFrontendModuleId()   Sets the current record's "frontend_module_id" value
 * @method Placeholder    setStructureId()        Sets the current record's "structure_id" value
 * @method Placeholder    setAction()             Sets the current record's "action" value
 * @method Placeholder    setName()               Sets the current record's "name" value
 * @method Placeholder    setPri()                Sets the current record's "pri" value
 * @method Placeholder    setFrontendModule()     Sets the current record's "FrontendModule" value
 * @method Placeholder    setStructure()          Sets the current record's "Structure" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePlaceholder extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('placeholder');
        $this->hasColumn('frontend_module_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('action', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'render',
             'length' => '50',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'default' => 'noname',
             'length' => '50',
             ));
        $this->hasColumn('pri', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FrontendModule', array(
             'local' => 'frontend_module_id',
             'foreign' => 'id'));

        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}