<?php

/**
 * BaseLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $abr
 * @property string $title_est
 * @property Currency $Currency
 * 
 * @method string   getUrl()       Returns the current record's "url" value
 * @method string   getAbr()       Returns the current record's "abr" value
 * @method string   getTitleEst()  Returns the current record's "title_est" value
 * @method Currency getCurrency()  Returns the current record's "Currency" value
 * @method Language setUrl()       Sets the current record's "url" value
 * @method Language setAbr()       Sets the current record's "abr" value
 * @method Language setTitleEst()  Sets the current record's "title_est" value
 * @method Language setCurrency()  Sets the current record's "Currency" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLanguage extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('language');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('abr', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('title_est', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Currency', array(
             'local' => 'id',
             'foreign' => 'language_id'));
    }
}