<?php

/**
 * BaseBannerGroupVsProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $banner_group_id
 * @property integer $product_id
 * @property BannerGroup $BannerGroup
 * @property Product $Product
 * 
 * @method integer              getBannerGroupId()   Returns the current record's "banner_group_id" value
 * @method integer              getProductId()       Returns the current record's "product_id" value
 * @method BannerGroup          getBannerGroup()     Returns the current record's "BannerGroup" value
 * @method Product              getProduct()         Returns the current record's "Product" value
 * @method BannerGroupVsProduct setBannerGroupId()   Sets the current record's "banner_group_id" value
 * @method BannerGroupVsProduct setProductId()       Sets the current record's "product_id" value
 * @method BannerGroupVsProduct setBannerGroup()     Sets the current record's "BannerGroup" value
 * @method BannerGroupVsProduct setProduct()         Sets the current record's "Product" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBannerGroupVsProduct extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner_group_vs_product');
        $this->hasColumn('banner_group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BannerGroup', array(
             'local' => 'banner_group_id',
             'foreign' => 'id'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));
    }
}