<?php

/**
 * BaseProductOrderBilling
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $country
 * @property string $city
 * @property string $street
 * @property string $zip
 * @property string $receiver
 * @property string $email
 * @property integer $order_id
 * @property ProductOrder $ProductOrder
 * 
 * @method string              getCountry()      Returns the current record's "country" value
 * @method string              getCity()         Returns the current record's "city" value
 * @method string              getStreet()       Returns the current record's "street" value
 * @method string              getZip()          Returns the current record's "zip" value
 * @method string              getReceiver()     Returns the current record's "receiver" value
 * @method string              getEmail()        Returns the current record's "email" value
 * @method integer             getOrderId()      Returns the current record's "order_id" value
 * @method ProductOrder        getProductOrder() Returns the current record's "ProductOrder" value
 * @method ProductOrderBilling setCountry()      Sets the current record's "country" value
 * @method ProductOrderBilling setCity()         Sets the current record's "city" value
 * @method ProductOrderBilling setStreet()       Sets the current record's "street" value
 * @method ProductOrderBilling setZip()          Sets the current record's "zip" value
 * @method ProductOrderBilling setReceiver()     Sets the current record's "receiver" value
 * @method ProductOrderBilling setEmail()        Sets the current record's "email" value
 * @method ProductOrderBilling setOrderId()      Sets the current record's "order_id" value
 * @method ProductOrderBilling setProductOrder() Sets the current record's "ProductOrder" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductOrderBilling extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_order_billing');
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('street', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('zip', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('receiver', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductOrder', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}