<?php

/**
 * BasePlaceholdersVsModules
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $placeholder
 * @property integer $frontend_module_id
 * @property FrontendModule $FrontendModule
 * 
 * @method string                getPlaceholder()        Returns the current record's "placeholder" value
 * @method integer               getFrontendModuleId()   Returns the current record's "frontend_module_id" value
 * @method FrontendModule        getFrontendModule()     Returns the current record's "FrontendModule" value
 * @method PlaceholdersVsModules setPlaceholder()        Sets the current record's "placeholder" value
 * @method PlaceholdersVsModules setFrontendModuleId()   Sets the current record's "frontend_module_id" value
 * @method PlaceholdersVsModules setFrontendModule()     Sets the current record's "FrontendModule" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePlaceholdersVsModules extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('placeholders_vs_modules');
        $this->hasColumn('placeholder', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('frontend_module_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FrontendModule', array(
             'local' => 'frontend_module_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}