<?php

/**
 * BaseParameterProductValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $param_id
 * @property integer $product_id
 * @property string $value
 * @property string $common_value
 * @property string $filename
 * @property string $common_filename
 * @property Parameter $Parameter
 * @property Product $Product
 * 
 * @method integer               getParamId()         Returns the current record's "param_id" value
 * @method integer               getProductId()       Returns the current record's "product_id" value
 * @method string                getValue()           Returns the current record's "value" value
 * @method string                getCommonValue()     Returns the current record's "common_value" value
 * @method string                getFilename()        Returns the current record's "filename" value
 * @method string                getCommonFilename()  Returns the current record's "common_filename" value
 * @method Parameter             getParameter()       Returns the current record's "Parameter" value
 * @method Product               getProduct()         Returns the current record's "Product" value
 * @method ParameterProductValue setParamId()         Sets the current record's "param_id" value
 * @method ParameterProductValue setProductId()       Sets the current record's "product_id" value
 * @method ParameterProductValue setValue()           Sets the current record's "value" value
 * @method ParameterProductValue setCommonValue()     Sets the current record's "common_value" value
 * @method ParameterProductValue setFilename()        Sets the current record's "filename" value
 * @method ParameterProductValue setCommonFilename()  Sets the current record's "common_filename" value
 * @method ParameterProductValue setParameter()       Sets the current record's "Parameter" value
 * @method ParameterProductValue setProduct()         Sets the current record's "Product" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseParameterProductValue extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parameter_product_value');
        $this->hasColumn('param_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 9999, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '9999',
             ));
        $this->hasColumn('common_value', 'string', 9999, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '9999',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('common_filename', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parameter', array(
             'local' => 'param_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'value',
              1 => 'filename',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $userid0 = new Doctrine_Template_Userid(array(
             'created' => 
             array(
              'name' => 'created_by',
              'type' => 'integer',
             ),
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'integer',
             ),
             ));
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($userid0);
    }
}