<?php

/**
 * BaseParameterTextfield
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseParameterTextfield extends Parameter
{
    public function setUp()
    {
        parent::setUp();
        
    }
}