<?php

/**
 * BaseAdminUserGroupVsStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $permission
 * @property integer $structure_id
 * @property integer $admin_user_group_id
 * @property Structure $Structure
 * @property AdminUserGroup $AdminUserGroup
 * 
 * @method string                    getName()                Returns the current record's "name" value
 * @method integer                   getPermission()          Returns the current record's "permission" value
 * @method integer                   getStructureId()         Returns the current record's "structure_id" value
 * @method integer                   getAdminUserGroupId()    Returns the current record's "admin_user_group_id" value
 * @method Structure                 getStructure()           Returns the current record's "Structure" value
 * @method AdminUserGroup            getAdminUserGroup()      Returns the current record's "AdminUserGroup" value
 * @method AdminUserGroupVsStructure setName()                Sets the current record's "name" value
 * @method AdminUserGroupVsStructure setPermission()          Sets the current record's "permission" value
 * @method AdminUserGroupVsStructure setStructureId()         Sets the current record's "structure_id" value
 * @method AdminUserGroupVsStructure setAdminUserGroupId()    Sets the current record's "admin_user_group_id" value
 * @method AdminUserGroupVsStructure setStructure()           Sets the current record's "Structure" value
 * @method AdminUserGroupVsStructure setAdminUserGroup()      Sets the current record's "AdminUserGroup" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAdminUserGroupVsStructure extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_user_group_vs_structure');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'noname',
             'length' => '50',
             ));
        $this->hasColumn('permission', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('admin_user_group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('AdminUserGroup', array(
             'local' => 'admin_user_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}