<?php

/**
 * BaseBackendModule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $module_name
 * @property string $action
 * @property string $title
 * @property string $credential
 * @property integer $frontend_module_id
 * @property FrontendModule $FrontendModule
 * 
 * @method string         getModuleName()         Returns the current record's "module_name" value
 * @method string         getAction()             Returns the current record's "action" value
 * @method string         getTitle()              Returns the current record's "title" value
 * @method string         getCredential()         Returns the current record's "credential" value
 * @method integer        getFrontendModuleId()   Returns the current record's "frontend_module_id" value
 * @method FrontendModule getFrontendModule()     Returns the current record's "FrontendModule" value
 * @method BackendModule  setModuleName()         Sets the current record's "module_name" value
 * @method BackendModule  setAction()             Sets the current record's "action" value
 * @method BackendModule  setTitle()              Sets the current record's "title" value
 * @method BackendModule  setCredential()         Sets the current record's "credential" value
 * @method BackendModule  setFrontendModuleId()   Sets the current record's "frontend_module_id" value
 * @method BackendModule  setFrontendModule()     Sets the current record's "FrontendModule" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBackendModule extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('backend_module');
        $this->hasColumn('module_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('action', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'index',
             'length' => '50',
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('credential', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'default' => '',
             'length' => '50',
             ));
        $this->hasColumn('frontend_module_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FrontendModule', array(
             'local' => 'frontend_module_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}