<?php

/**
 * BaseParameterOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $param_id
 * @property string $title
 * @property string $name
 * @property integer $pri
 * @property Parameter $Parameter
 * @property Doctrine_Collection $Product
 * @property Doctrine_Collection $ParameterProductOptions
 * 
 * @method integer             getParamId()                 Returns the current record's "param_id" value
 * @method string              getTitle()                   Returns the current record's "title" value
 * @method string              getName()                    Returns the current record's "name" value
 * @method integer             getPri()                     Returns the current record's "pri" value
 * @method Parameter           getParameter()               Returns the current record's "Parameter" value
 * @method Doctrine_Collection getProduct()                 Returns the current record's "Product" collection
 * @method Doctrine_Collection getParameterProductOptions() Returns the current record's "ParameterProductOptions" collection
 * @method ParameterOption     setParamId()                 Sets the current record's "param_id" value
 * @method ParameterOption     setTitle()                   Sets the current record's "title" value
 * @method ParameterOption     setName()                    Sets the current record's "name" value
 * @method ParameterOption     setPri()                     Sets the current record's "pri" value
 * @method ParameterOption     setParameter()               Sets the current record's "Parameter" value
 * @method ParameterOption     setProduct()                 Sets the current record's "Product" collection
 * @method ParameterOption     setParameterProductOptions() Sets the current record's "ParameterProductOptions" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseParameterOption extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parameter_option');
        $this->hasColumn('param_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('pri', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Parameter', array(
             'local' => 'param_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Product', array(
             'refClass' => 'ParameterProductOption',
             'local' => 'option_id',
             'foreign' => 'product_id'));

        $this->hasMany('ParameterProductOption as ParameterProductOptions', array(
             'local' => 'id',
             'foreign' => 'option_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $userid0 = new Doctrine_Template_Userid(array(
             'created' => 
             array(
              'name' => 'created_by',
              'type' => 'integer',
             ),
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'integer',
             ),
             ));
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($userid0);
    }
}