<?php

/**
 * BasePublicUserAddresses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $public_user_id
 * @property string $title
 * @property string $name
 * @property string $address
 * @property string $city
 * @property string $state
 * @property string $country
 * @property string $zip
 * @property PublicUser $PublicUser
 * 
 * @method integer             getPublicUserId()   Returns the current record's "public_user_id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getAddress()        Returns the current record's "address" value
 * @method string              getCity()           Returns the current record's "city" value
 * @method string              getState()          Returns the current record's "state" value
 * @method string              getCountry()        Returns the current record's "country" value
 * @method string              getZip()            Returns the current record's "zip" value
 * @method PublicUser          getPublicUser()     Returns the current record's "PublicUser" value
 * @method PublicUserAddresses setPublicUserId()   Sets the current record's "public_user_id" value
 * @method PublicUserAddresses setTitle()          Sets the current record's "title" value
 * @method PublicUserAddresses setName()           Sets the current record's "name" value
 * @method PublicUserAddresses setAddress()        Sets the current record's "address" value
 * @method PublicUserAddresses setCity()           Sets the current record's "city" value
 * @method PublicUserAddresses setState()          Sets the current record's "state" value
 * @method PublicUserAddresses setCountry()        Sets the current record's "country" value
 * @method PublicUserAddresses setZip()            Sets the current record's "zip" value
 * @method PublicUserAddresses setPublicUser()     Sets the current record's "PublicUser" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePublicUserAddresses extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('public_user_addresses');
        $this->hasColumn('public_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'new address',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('state', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('zip', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PublicUser', array(
             'local' => 'public_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}