<?php

/**
 * BaseParameterGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property Doctrine_Collection $Parameters
 * @property Doctrine_Collection $ProductGroupParameterGroups
 * 
 * @method string              getName()                        Returns the current record's "name" value
 * @method string              getTitle()                       Returns the current record's "title" value
 * @method Doctrine_Collection getParameters()                  Returns the current record's "Parameters" collection
 * @method Doctrine_Collection getProductGroupParameterGroups() Returns the current record's "ProductGroupParameterGroups" collection
 * @method ParameterGroup      setName()                        Sets the current record's "name" value
 * @method ParameterGroup      setTitle()                       Sets the current record's "title" value
 * @method ParameterGroup      setParameters()                  Sets the current record's "Parameters" collection
 * @method ParameterGroup      setProductGroupParameterGroups() Sets the current record's "ProductGroupParameterGroups" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseParameterGroup extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parameter_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Parameter as Parameters', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('ProductGroupVsParameterGroup as ProductGroupParameterGroups', array(
             'local' => 'id',
             'foreign' => 'paramgroup_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $userid0 = new Doctrine_Template_Userid(array(
             'created' => 
             array(
              'name' => 'created_by',
              'type' => 'integer',
             ),
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'integer',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
        $this->actAs($i18n0);
        $this->actAs($userid0);
    }
}