<?php

/**
 * BaseShippingZoneInterval
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $my_zone_id
 * @property integer $start
 * @property integer $end
 * @property float $price
 * @property ShippingZone $ShippingZone
 * 
 * @method integer              getMyZoneId()     Returns the current record's "my_zone_id" value
 * @method integer              getStart()        Returns the current record's "start" value
 * @method integer              getEnd()          Returns the current record's "end" value
 * @method float                getPrice()        Returns the current record's "price" value
 * @method ShippingZone         getShippingZone() Returns the current record's "ShippingZone" value
 * @method ShippingZoneInterval setMyZoneId()     Sets the current record's "my_zone_id" value
 * @method ShippingZoneInterval setStart()        Sets the current record's "start" value
 * @method ShippingZoneInterval setEnd()          Sets the current record's "end" value
 * @method ShippingZoneInterval setPrice()        Sets the current record's "price" value
 * @method ShippingZoneInterval setShippingZone() Sets the current record's "ShippingZone" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseShippingZoneInterval extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_zone_interval');
        $this->hasColumn('my_zone_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('end', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ShippingZone', array(
             'local' => 'my_zone_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}