<?php

/**
 * BaseProductVsProductGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $product_id
 * @property ProductGroup $ProductGroup
 * @property Product $Product
 * 
 * @method integer               getGroupId()      Returns the current record's "group_id" value
 * @method integer               getProductId()    Returns the current record's "product_id" value
 * @method ProductGroup          getProductGroup() Returns the current record's "ProductGroup" value
 * @method Product               getProduct()      Returns the current record's "Product" value
 * @method ProductVsProductGroup setGroupId()      Sets the current record's "group_id" value
 * @method ProductVsProductGroup setProductId()    Sets the current record's "product_id" value
 * @method ProductVsProductGroup setProductGroup() Sets the current record's "ProductGroup" value
 * @method ProductVsProductGroup setProduct()      Sets the current record's "Product" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductVsProductGroup extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_vs_product_group');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}