<?php

/**
 * BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $pri
 * @property string $type
 * @property string $link
 * @property string $content
 * @property string $flash_vars
 * @property boolean $is_active
 * @property integer $displayed
 * @property integer $clicked
 * @property string $file
 * @property integer $width
 * @property integer $height
 * @property integer $banner_group_id
 * @property BannerGroup $BannerGroup
 * 
 * @method string      getName()            Returns the current record's "name" value
 * @method integer     getPri()             Returns the current record's "pri" value
 * @method string      getType()            Returns the current record's "type" value
 * @method string      getLink()            Returns the current record's "link" value
 * @method string      getContent()         Returns the current record's "content" value
 * @method string      getFlashVars()       Returns the current record's "flash_vars" value
 * @method boolean     getIsActive()        Returns the current record's "is_active" value
 * @method integer     getDisplayed()       Returns the current record's "displayed" value
 * @method integer     getClicked()         Returns the current record's "clicked" value
 * @method string      getFile()            Returns the current record's "file" value
 * @method integer     getWidth()           Returns the current record's "width" value
 * @method integer     getHeight()          Returns the current record's "height" value
 * @method integer     getBannerGroupId()   Returns the current record's "banner_group_id" value
 * @method BannerGroup getBannerGroup()     Returns the current record's "BannerGroup" value
 * @method Banner      setName()            Sets the current record's "name" value
 * @method Banner      setPri()             Sets the current record's "pri" value
 * @method Banner      setType()            Sets the current record's "type" value
 * @method Banner      setLink()            Sets the current record's "link" value
 * @method Banner      setContent()         Sets the current record's "content" value
 * @method Banner      setFlashVars()       Sets the current record's "flash_vars" value
 * @method Banner      setIsActive()        Sets the current record's "is_active" value
 * @method Banner      setDisplayed()       Sets the current record's "displayed" value
 * @method Banner      setClicked()         Sets the current record's "clicked" value
 * @method Banner      setFile()            Sets the current record's "file" value
 * @method Banner      setWidth()           Sets the current record's "width" value
 * @method Banner      setHeight()          Sets the current record's "height" value
 * @method Banner      setBannerGroupId()   Sets the current record's "banner_group_id" value
 * @method Banner      setBannerGroup()     Sets the current record's "BannerGroup" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBanner extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('pri', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'default',
             'length' => '255',
             ));
        $this->hasColumn('link', 'string', 400, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '400',
             ));
        $this->hasColumn('content', 'string', 5000, array(
             'type' => 'string',
             'notnull' => false,
             'default' => '',
             'length' => '5000',
             ));
        $this->hasColumn('flash_vars', 'string', 400, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '400',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('displayed', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('clicked', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('banner_group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->setSubClasses(array(
             'BannerGif' => 
             array(
              'type' => 'gif',
             ),
             'BannerFlash' => 
             array(
              'type' => 'flash',
             ),
             'BannerHtml' => 
             array(
              'type' => 'html',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BannerGroup', array(
             'local' => 'banner_group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}