<?php

/**
 * BaseShippingZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $fake
 * @property Doctrine_Collection $Intervals
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getFake()      Returns the current record's "fake" value
 * @method Doctrine_Collection getIntervals() Returns the current record's "Intervals" collection
 * @method ShippingZone        setName()      Sets the current record's "name" value
 * @method ShippingZone        setFake()      Sets the current record's "fake" value
 * @method ShippingZone        setIntervals() Sets the current record's "Intervals" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseShippingZone extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_zone');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('fake', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ShippingZoneInterval as Intervals', array(
             'local' => 'id',
             'foreign' => 'my_zone_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}