<?php

/**
 * BaseCatalogue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cat_id
 * @property string $name
 * @property string $source_lang
 * @property string $target_lang
 * @property integer $date_created
 * @property integer $date_modified
 * @property string $author
 * @property Doctrine_Collection $Units
 * 
 * @method integer             getCatId()         Returns the current record's "cat_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getSourceLang()    Returns the current record's "source_lang" value
 * @method string              getTargetLang()    Returns the current record's "target_lang" value
 * @method integer             getDateCreated()   Returns the current record's "date_created" value
 * @method integer             getDateModified()  Returns the current record's "date_modified" value
 * @method string              getAuthor()        Returns the current record's "author" value
 * @method Doctrine_Collection getUnits()         Returns the current record's "Units" collection
 * @method Catalogue           setCatId()         Sets the current record's "cat_id" value
 * @method Catalogue           setName()          Sets the current record's "name" value
 * @method Catalogue           setSourceLang()    Sets the current record's "source_lang" value
 * @method Catalogue           setTargetLang()    Sets the current record's "target_lang" value
 * @method Catalogue           setDateCreated()   Sets the current record's "date_created" value
 * @method Catalogue           setDateModified()  Sets the current record's "date_modified" value
 * @method Catalogue           setAuthor()        Sets the current record's "author" value
 * @method Catalogue           setUnits()         Sets the current record's "Units" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCatalogue extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catalogue');
        $this->hasColumn('cat_id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => '63',
             ));
        $this->hasColumn('source_lang', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => '63',
             ));
        $this->hasColumn('target_lang', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => '63',
             ));
        $this->hasColumn('date_created', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('date_modified', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('author', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => '63',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TransUnit as Units', array(
             'local' => 'cat_id',
             'foreign' => 'cat_id'));
    }
}