<?php

/**
 * BaseProductOrderVsProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $order_id
 * @property ProductOrder $ProductOrder
 * @property Product $Product
 * 
 * @method integer               getProductId()    Returns the current record's "product_id" value
 * @method integer               getOrderId()      Returns the current record's "order_id" value
 * @method ProductOrder          getProductOrder() Returns the current record's "ProductOrder" value
 * @method Product               getProduct()      Returns the current record's "Product" value
 * @method ProductOrderVsProduct setProductId()    Sets the current record's "product_id" value
 * @method ProductOrderVsProduct setOrderId()      Sets the current record's "order_id" value
 * @method ProductOrderVsProduct setProductOrder() Sets the current record's "ProductOrder" value
 * @method ProductOrderVsProduct setProduct()      Sets the current record's "Product" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductOrderVsProduct extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_order_vs_product');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('order_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductOrder', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}