<?php

/**
 * BaseShop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property text $address
 * 
 * @method string getTitle()   Returns the current record's "title" value
 * @method text   getAddress() Returns the current record's "address" value
 * @method Shop   setTitle()   Sets the current record's "title" value
 * @method Shop   setAddress() Sets the current record's "address" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseShop extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('address', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'address',
             ),
             ));
        $this->actAs($i18n0);
    }
}