<?php

/**
 * BaseProductGroupVsStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $structure_id
 * @property ProductGroup $ProductGroup
 * @property Structure $Structure
 * 
 * @method integer                 getGroupId()      Returns the current record's "group_id" value
 * @method integer                 getStructureId()  Returns the current record's "structure_id" value
 * @method ProductGroup            getProductGroup() Returns the current record's "ProductGroup" value
 * @method Structure               getStructure()    Returns the current record's "Structure" value
 * @method ProductGroupVsStructure setGroupId()      Sets the current record's "group_id" value
 * @method ProductGroupVsStructure setStructureId()  Sets the current record's "structure_id" value
 * @method ProductGroupVsStructure setProductGroup() Sets the current record's "ProductGroup" value
 * @method ProductGroupVsStructure setStructure()    Sets the current record's "Structure" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductGroupVsStructure extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_group_vs_structure');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('structure_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Structure', array(
             'local' => 'structure_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}