<?php

/**
 * BaseStructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $parameter
 * @property string $picture
 * @property string $content
 * @property boolean $inherits_layout
 * @property string $type
 * @property string $description
 * @property string $pageTitle
 * @property string $layout
 * @property string $metaDescription
 * @property string $metaKeywords
 * @property string $status
 * @property boolean $is_first
 * @property string $lang
 * @property integer $pri
 * @property integer $parentID
 * @property boolean $isHidden
 * @property Structure $Parent
 * @property Doctrine_Collection $AdminUserGroup
 * @property Doctrine_Collection $Structure
 * 
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getParameter()             Returns the current record's "parameter" value
 * @method string              getPicture()               Returns the current record's "picture" value
 * @method string              getContent()               Returns the current record's "content" value
 * @method boolean             getInheritsLayout()        Returns the current record's "inherits_layout" value
 * @method string              getType()                  Returns the current record's "type" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getPageTitle()             Returns the current record's "pageTitle" value
 * @method string              getLayout()                Returns the current record's "layout" value
 * @method string              getMetaDescription()       Returns the current record's "metaDescription" value
 * @method string              getMetaKeywords()          Returns the current record's "metaKeywords" value
 * @method string              getStatus()                Returns the current record's "status" value
 * @method boolean             getIsFirst()               Returns the current record's "is_first" value
 * @method string              getLang()                  Returns the current record's "lang" value
 * @method integer             getPri()                   Returns the current record's "pri" value
 * @method integer             getParentID()              Returns the current record's "parentID" value
 * @method boolean             getIsHidden()              Returns the current record's "isHidden" value
 * @method Structure           getParent()                Returns the current record's "Parent" value
 * @method Doctrine_Collection getAdminUserGroup()        Returns the current record's "AdminUserGroup" collection
 * @method Doctrine_Collection getStructureBannerGroups() Returns the current record's "StructureBannerGroups" collection
 * @method Doctrine_Collection getStructureNewsGroup()    Returns the current record's "StructureNewsGroup" collection
 * @method Doctrine_Collection getPlaceholder()           Returns the current record's "Placeholder" collection
 * @method Doctrine_Collection getStructure()             Returns the current record's "Structure" collection
 * @method Structure           setTitle()                 Sets the current record's "title" value
 * @method Structure           setParameter()             Sets the current record's "parameter" value
 * @method Structure           setPicture()               Sets the current record's "picture" value
 * @method Structure           setContent()               Sets the current record's "content" value
 * @method Structure           setInheritsLayout()        Sets the current record's "inherits_layout" value
 * @method Structure           setType()                  Sets the current record's "type" value
 * @method Structure           setDescription()           Sets the current record's "description" value
 * @method Structure           setPageTitle()             Sets the current record's "pageTitle" value
 * @method Structure           setLayout()                Sets the current record's "layout" value
 * @method Structure           setMetaDescription()       Sets the current record's "metaDescription" value
 * @method Structure           setMetaKeywords()          Sets the current record's "metaKeywords" value
 * @method Structure           setStatus()                Sets the current record's "status" value
 * @method Structure           setIsFirst()               Sets the current record's "is_first" value
 * @method Structure           setLang()                  Sets the current record's "lang" value
 * @method Structure           setPri()                   Sets the current record's "pri" value
 * @method Structure           setParentID()              Sets the current record's "parentID" value
 * @method Structure           setIsHidden()              Sets the current record's "isHidden" value
 * @method Structure           setParent()                Sets the current record's "Parent" value
 * @method Structure           setAdminUserGroup()        Sets the current record's "AdminUserGroup" collection
 * @method Structure           setStructureBannerGroups() Sets the current record's "StructureBannerGroups" collection
 * @method Structure           setStructureNewsGroup()    Sets the current record's "StructureNewsGroup" collection
 * @method Structure           setPlaceholder()           Sets the current record's "Placeholder" collection
 * @method Structure           setStructure()             Sets the current record's "Structure" collectionBannerGroups
 * @property Doctrine_Collection $Structure
 * 
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getParameter()             Returns the current record's "parameter" value
 * @method string              getPicture()               Returns the current record's "picture" value
 * @method string              getContent()               Returns the current record's "content" value
 * @method boolean             getInheritsLayout()        Returns the current record's "inherits_layout" value
 * @method string              getType()                  Returns the current record's "type" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getPageTitle()             Returns the current record's "pageTitle" value
 * @method string              getLayout()                Returns the current record's "layout" value
 * @method string              getMetaDescription()       Returns the current record's "metaDescription" value
 * @method string              getMetaKeywords()          Returns the current record's "metaKeywords" value
 * @method string              getStatus()                Returns the current record's "status" value
 * @method boolean             getIsFirst()               Returns the current record's "is_first" value
 * @method string              getLang()                  Returns the current record's "lang" value
 * @method integer             getPri()                   Returns the current record's "pri" value
 * @method integer             getParentID()              Returns the current record's "parentID" value
 * @method boolean             getIsHidden()              Returns the current record's "isHidden" value
 * @method Structure           getParent()                Returns the current record's "Parent" value
 * @method Doctrine_Collection getAdminUserGroup()        Returns the current record's "AdminUserGroup" collection
 * @method Doctrine_Collection getStructureBannerGroups() Returns the current record's "StructureBannerGroups" collection
 * @method Doctrine_Collection getStructureNewsGroup()    Returns the current record's "StructureNewsGroup" collection
 * @method Doctrine_Collection getPlaceholder()           Returns the current record's "Placeholder" collection
 * @method Doctrine_Collection getStructure()             Returns the current record's "Structure" collection
 * @method Structure           setTitle()                 Sets the current record's "title" value
 * @method Structure           setParameter()             Sets the current record's "parameter" value
 * @method Structure           setPicture()               Sets the current record's "picture" value
 * @method Structure           setContent()               Sets the current record's "content" value
 * @method Structure           setInheritsLayout()        Sets the current record's "inherits_layout" value
 * @method Structure           setType()                  Sets the current record's "type" value
 * @method Structure           setDescription()           Sets the current record's "description" value
 * @method Structure           setPageTitle()             Sets the current record's "pageTitle" value
 * @method Structure           setLayout()                Sets the current record's "layout" value
 * @method Structure           setMetaDescription()       Sets the current record's "metaDescription" value
 * @method Structure           setMetaKeywords()          Sets the current record's "metaKeywords" value
 * @method Structure           setStatus()                Sets the current record's "status" value
 * @method Structure           setIsFirst()               Sets the current record's "is_first" value
 * @method Structure           setLang()                  Sets the current record's "lang" value
 * @method Structure           setPri()                   Sets the current record's "pri" value
 * @method Structure           setParentID()              Sets the current record's "parentID" value
 * @method Structure           setIsHidden()              Sets the current record's "isHidden" value
 * @method Structure           setParent()                Sets the current record's "Parent" value
 * @method Structure           setAdminUserGroup()        Sets the current record's "AdminUserGroup" collection
 * @method Structure           setStructureBannerGroups() Sets the current record's "StructureBannerGroups" collection
 * @method Structure           setStructureNewsGroup()    Sets the current record's "StructureNewsGroup" collection
 * @method Structure           setPlaceholder()           Sets the current record's "Placeholder" collection
 * @method Structure           setStructure()             Sets the current record's "Structure" collectionNewsGroup
 * @property Doctrine_Collection $Placeholder
 * @property Doctrine_Collection $Structure
 * 
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getParameter()             Returns the current record's "parameter" value
 * @method string              getPicture()               Returns the current record's "picture" value
 * @method string              getContent()               Returns the current record's "content" value
 * @method boolean             getInheritsLayout()        Returns the current record's "inherits_layout" value
 * @method string              getType()                  Returns the current record's "type" value
 * @method string              getDescription()           Returns the current record's "description" value
 * @method string              getPageTitle()             Returns the current record's "pageTitle" value
 * @method string              getLayout()                Returns the current record's "layout" value
 * @method string              getMetaDescription()       Returns the current record's "metaDescription" value
 * @method string              getMetaKeywords()          Returns the current record's "metaKeywords" value
 * @method string              getStatus()                Returns the current record's "status" value
 * @method boolean             getIsFirst()               Returns the current record's "is_first" value
 * @method string              getLang()                  Returns the current record's "lang" value
 * @method integer             getPri()                   Returns the current record's "pri" value
 * @method integer             getParentID()              Returns the current record's "parentID" value
 * @method boolean             getIsHidden()              Returns the current record's "isHidden" value
 * @method Structure           getParent()                Returns the current record's "Parent" value
 * @method Doctrine_Collection getAdminUserGroup()        Returns the current record's "AdminUserGroup" collection
 * @method Doctrine_Collection getStructureBannerGroups() Returns the current record's "StructureBannerGroups" collection
 * @method Doctrine_Collection getStructureNewsGroup()    Returns the current record's "StructureNewsGroup" collection
 * @method Doctrine_Collection getPlaceholder()           Returns the current record's "Placeholder" collection
 * @method Doctrine_Collection getStructure()             Returns the current record's "Structure" collection
 * @method Structure           setTitle()                 Sets the current record's "title" value
 * @method Structure           setParameter()             Sets the current record's "parameter" value
 * @method Structure           setPicture()               Sets the current record's "picture" value
 * @method Structure           setContent()               Sets the current record's "content" value
 * @method Structure           setInheritsLayout()        Sets the current record's "inherits_layout" value
 * @method Structure           setType()                  Sets the current record's "type" value
 * @method Structure           setDescription()           Sets the current record's "description" value
 * @method Structure           setPageTitle()             Sets the current record's "pageTitle" value
 * @method Structure           setLayout()                Sets the current record's "layout" value
 * @method Structure           setMetaDescription()       Sets the current record's "metaDescription" value
 * @method Structure           setMetaKeywords()          Sets the current record's "metaKeywords" value
 * @method Structure           setStatus()                Sets the current record's "status" value
 * @method Structure           setIsFirst()               Sets the current record's "is_first" value
 * @method Structure           setLang()                  Sets the current record's "lang" value
 * @method Structure           setPri()                   Sets the current record's "pri" value
 * @method Structure           setParentID()              Sets the current record's "parentID" value
 * @method Structure           setIsHidden()              Sets the current record's "isHidden" value
 * @method Structure           setParent()                Sets the current record's "Parent" value
 * @method Structure           setAdminUserGroup()        Sets the current record's "AdminUserGroup" collection
 * @method Structure           setStructureBannerGroups() Sets the current record's "StructureBannerGroups" collection
 * @method Structure           setStructureNewsGroup()    Sets the current record's "StructureNewsGroup" collection
 * @method Structure           setPlaceholder()           Sets the current record's "Placeholder" collection
 * @method Structure           setStructure()             Sets the current record's "Structure" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseStructure extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('structure');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('parameter', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => '255',
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', 9999, array(
             'type' => 'string',
             'notnull' => false,
             'default' => '',
             'length' => '9999',
             ));
        $this->hasColumn('inherits_layout', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'standard',
             'length' => '50',
             ));
        $this->hasColumn('description', 'string', 700, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '700',
             ));
        $this->hasColumn('pageTitle', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('layout', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'layout',
             'length' => '255',
             ));
        $this->hasColumn('metaDescription', 'string', 500, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '500',
             ));
        $this->hasColumn('metaKeywords', 'string', 700, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '700',
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 0,
             'length' => '255',
             ));
        $this->hasColumn('is_first', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('pri', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('parentID', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('isHidden', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('orderBy', 'lft ASC');

        $this->setSubClasses(array(
             'StructureLanguage' => 
             array(
              'type' => 'lang',
             ),
             'StructureShop' => 
             array(
              'type' => 'shop',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Structure as Parent', array(
             'local' => 'parentid',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('AdminUserGroupVsStructure as AdminUserGroup', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('BannerGroupVsStructure as StructureBannerGroups', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('NewsGroupVsStructure as StructureNewsGroup', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('Placeholder', array(
             'local' => 'id',
             'foreign' => 'structure_id'));

        $this->hasMany('Structure', array(
             'local' => 'id',
             'foreign' => 'parentid'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => false,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet();
        $userid0 = new Doctrine_Template_Userid(array(
             'created' => 
             array(
              'name' => 'created_by',
              'type' => 'integer',
             ),
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'integer',
             ),
             ));
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
        $this->actAs($userid0);
    }
}