<?php

/**
 * BaseCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property decimal $factor
 * @property string $symbol
 * @property string $abbr
 * @property boolean $prefix
 * @property integer $language_id
 * @property Language $Language
 * 
 * @method string   getName()        Returns the current record's "name" value
 * @method decimal  getFactor()      Returns the current record's "factor" value
 * @method string   getSymbol()      Returns the current record's "symbol" value
 * @method string   getAbbr()        Returns the current record's "abbr" value
 * @method boolean  getPrefix()      Returns the current record's "prefix" value
 * @method integer  getLanguageId()  Returns the current record's "language_id" value
 * @method Language getLanguage()    Returns the current record's "Language" value
 * @method Currency setName()        Sets the current record's "name" value
 * @method Currency setFactor()      Sets the current record's "factor" value
 * @method Currency setSymbol()      Sets the current record's "symbol" value
 * @method Currency setAbbr()        Sets the current record's "abbr" value
 * @method Currency setPrefix()      Sets the current record's "prefix" value
 * @method Currency setLanguageId()  Sets the current record's "language_id" value
 * @method Currency setLanguage()    Sets the current record's "Language" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCurrency extends BaseDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('currency');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('factor', 'decimal', 18, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'default' => 1,
             'length' => '18',
             ));
        $this->hasColumn('symbol', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '255',
             ));
        $this->hasColumn('abbr', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('prefix', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));
    }
}