<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/11/15 15:23:36
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
    ),
  ),
);
