<?php

/**
 * NewItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class NewItem extends BaseNewItem
{

	public function postSave($evt = null){
		Doctrine::getConnectionByTableName($this->getTable()->getTableName())->setAttribute(Doctrine_Core::ATTR_HYDRATE_OVERWRITE, false); // we do not want to refresh our records
		$this->updateLuceneIndex();
		Doctrine::getConnectionByTableName($this->getTable()->getTableName())->setAttribute(Doctrine_Core::ATTR_HYDRATE_OVERWRITE, true);
	}


	public function updateLuceneIndex(){

		//delete existing entries
		$index = $this->getTable()->getLuceneIndex();



		// remove existing entries
		foreach ($index->find('pk:'.$this->getId()) as $hit){
		  $index->delete($hit->id);
		}



		// create new Lucene document
		$doc = new Zend_Search_Lucene_Document();

		// store product primary key to identify it in the search results
  		$doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));
		
		$doc->addField(Zend_Search_Lucene_Field::UnStored('description', $this->getDescription(), 'utf-8'));
		$doc->addField(Zend_Search_Lucene_Field::UnStored('content', strip_tags($this->getContent()), 'utf-8'));

		// add product to the index
		$index->addDocument($doc);
		$index->commit();

	}
	
	public static function getTypes(){
		return array( 
			'default' => 'Tavaline',
			'hot' => 'Kuum'
		);
	}
	
	public function getNewGroupsForForm(){
		
		if( $this->NewsGroup ){
			return $this->NewsGroup->getName();
		}
		
	}
	
	public function getPriForm(){
		$form =<<<EOD
		<input type="text" size=2 style="background-color:#EFEFEF;border:1px solid #777777;text-align: center; " name="product_pri[{$this->id}]" value="{$this->pri}" />	
EOD;
	return $form;
	}

}