<?php

/**
 * ParameterHtml
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ParameterHtml extends BaseParameterHtml
{

	
  public function createAndGetParamValueForm(  $product = null ){
  	
  	  	$this->setParamValueForm( new ParameterProductValueHTMLForm( 
  					Doctrine::getTable('ParameterProductValue')
  						->getObjectForProductAndParameter( $product, $this ) ) );
  						
	  	return $this->getParamValueForm();

  }

}