<?php

/**
 * ProductFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ProductFile extends BaseProductFile
{
	public function getSameLevelNodes(){
		return $this->getTable()->createQuery()
			->from('ProductFile pf')
			->where('pf.Product.id = ?', $this->getProductId())
			->execute();
	}

        public function renderDownloadLink(){
            return '/uploads' . $this->getFile();
        }


        public function renderIconSrc(){

            $result = '';

            switch($this->getExtension()){
                case 'pdf':
                    $result = '/olly/img/pdf.png';
                    break;
                default:
                    $result = '/olly/img/file_icon.png';
            }

            return $result;
        }


        public function getExtension(){
            return @end(explode('.', basename($this->getFile())));
        }
}
