<?php

/**
 * ProductExemplarVsPublicUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductExemplarVsPublicUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductExemplarVsPublicUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductExemplarVsPublicUser');
    }
}