<?php

/**
 * ProductPictures
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ProductPictures extends BaseProductPictures
{
	public function getSameLevelNodes()
	{
		return $this->getTable()->createQuery()
			->from('ProductPictures pp')
			->where('pp.Product.id = ?', $this->getProductId())
			->execute();
	}
}