<?php

/**
 * ProductExemplar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductExemplar extends BaseProductExemplar
{
	public function getName(){
		return $this->getProduct()->getName();
	}
}
