<?php

/**
 * StructureLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class StructureLanguage extends Structure
{
	
	public function getCustomForm()
	{
		return new StructureLanguageFormEdit( $this );		
	}
	
	
	
	
	public function preInsert( $obj ){
		$obj->slug = 123;
		$this->slug = 123;
		//exit;
	}
	
	
	
//	public function getSlug(){
//		return $this->getLang();
//	}
//	
//	

	
	
	
//	public function postSave(){
//		echo $this->slug;
//		exit;
//	}
	
//	public function getSlug(){
//		return $this->getLang();
//	}
	
//	public function preUpdate( $obj )
//	{
//		
//	}
	
//	public function postUpdate( $obj ){;
//		parent::postUpdate( $obj );
//	}
	
	public function setUrl( $url ){
		//$this->setSlug( $url );
	}
	
	public function setSlug( $url ){
		if( $this->getLang() )
			$this->_set('slug', $this->getLang() );
		
	}
	

}