generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProductOrder
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product_order
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          is_archived: {label: Arvhived ?}
          created_at: {label: Created}
          order_number: {label: Number}
      list:
          object_actions:
              _edit: ~
              invoice: {action: invoice}
              _delete: ~
          display: [=order_number,=status,has_notes,created_at, is_archived]
          sort: [created_at]
          batch_actions:
              _delete: ~
              archive: {label: archive / unarchive}
      filter:
          display: [order_number,status,is_archived]
      form:    ~
      edit:    ~
      new:     ~
