generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Parameter
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          parameter
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
       display: [title]
      filter:
       display: [group_id]
      form:    ~
      edit:    ~
      new:     ~
