generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TransUnitVariable
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          trans_unit_variable
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~ 
      list:
          display: [=variable, multilang]
      filter:
          display: [variable,multilang]
      form:    ~
      edit:    ~
      new:     ~
