<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addjobeetaffiliate extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('jobeet_affiliate', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 255,
             ),
             'token' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('jobeet_affiliate');
    }
}