all:  
  mailer:
      class: sfMailer
      param:
        logging:           %SF_LOGGING_ENABLED%
        charset:           %SF_CHARSET%
        delivery_strategy: realtime
        transport:
          class: Swift_SmtpTransport
          param:
            host: smtp.gmail.com
            port: 465
            encryption: ssl
            username: aneto1@gmail.com
            password: foo2008gmail1