generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProductComment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product_comment
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          display: [=name,=message,ip,product_id,created_at]
      filter:
          display: [ip,message]
      form:    ~
      edit:    ~
      new:     ~
