<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/15 13:28:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=d765.mysql.zone.ee;dbname=d765sd32919',
  'username' => 'd765sa38624',
  'password' => 'kiV3X5',
  'name' => 'doctrine',
)),);
