<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addjobeetcategory extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('jobeet_category', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 255,
             ),
             'excerpt' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => false,
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('jobeet_category');
    }
}