<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addjobeetcategoryaffiliate extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('jobeet_category_affiliate', array(
             'category_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'affiliate_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'category_id',
              1 => 'affiliate_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('jobeet_category_affiliate');
    }
}