generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BannerGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          banner_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, type , is_active]
      filter:
        display: [name, type, relatives]
      form:    ~
      edit:    ~
      new:     ~
