<?php

/**
 * BannerGroup
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class BannerGroup extends BaseBannerGroup
{

	public static function getTypes(){
		return array(	'default' => 'Default',
						'special' => 'Special',
						'logos' => 'Logos',
						'right' => 'Right',
						'left' => 'Left',
						'left2' => 'Left2',
						'social' => 'Social',
						'right_bottom' => 'Right bottom',
						'header' => 'Header',);
	}

	public function updateConnections( $connections ){
		$this->deleteConnections();
		foreach( $connections as $rel ){
			$obj = new BannerGroupVsStructure();
			$obj->fromArray(array( 'banner_group_id' => $this->id, 'structure_id' => $rel  ));
			$obj->save();
		}
	}

	public function updateProductGroupConnections( $connections ){
		$this->deleteProductGroupConnections();

		foreach( $connections as $rel ){
			$obj = new BannerGroupVsProductGroup();
			$obj->fromArray( array( 'product_group_id' => $rel, 'banner_group_id' => $this->id ) );
			$obj->save();
		}
	}


	public function deleteProductGroupConnections(){
		foreach( $this->BannerGroups as $rel ){
			$rel->delete();
		}
	}

	public function deleteConnections(){
		foreach( $this->StructureBannerGroups as $rel ){
			$rel->delete();
		}
	}



}