<?php

/**
 * NewsGroup
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class NewsGroup extends BaseNewsGroup
{

	public static function getTypes(){
		return array(	'default' => 'Tavaline',
						'special' => 'Spetsiaalne',
						'slider' => 'Slider',
						'tab' => 'Tab',
						'row' => 'Row',
						'column' => 'Column',
					);
	}

	public function updateConnections( $connections ){
		$this->deleteConnections();
		foreach( $connections as $rel ){
			$obj = new NewsGroupVsStructure();
			$obj->fromArray(array( 'group_id' => $this->id, 'structure_id' => $rel  ));
			$obj->save();
		}
	}


	public function deleteConnections(){
		foreach( $this->StructureNewsGroup as $rel ){
			$rel->delete();
		}
	}

	public function isPermittedForUser( $userObj, $permLevel )
	{

		$q = Doctrine_Query::create()
			->from('Structure s ')
			->innerJoin('s.StructureNewsGroup sng WITH sng.group_id = ? ', $this->id);

		$isPermitted = true;
		foreach( $q->execute() as $struct ){
			$isPermitted = $isPermitted && $struct->isPermittedForUser( $userObj, $permLevel );
		}

		return $isPermitted;
	}

	public function getPriForm(){
		$form =<<<EOD
		<input type="text" size=2 style="background-color:#EFEFEF;border:1px solid #777777;text-align: center; " name="product_pri[{$this->id}]" value="{$this->pri}" />
EOD;
	return $form;
	}

}