<?php

/**
 * ParameterGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ParameterGroup extends BaseParameterGroup
{
	
//	public function getTitle(){
//		return $this->title;
////		if( strlen( $this->getName() ) === 0 ){
////			return $this->Translation[sfConfig::get('sf_default_culture')]->name;
////		}else
////			return $this->getName();
//		
//	}
	
	
	public function getParameters(){
		return $this->getTable()->createQuery('parameters')
					->select('p.*')
					->from('Parameter p')
					->innerJoin('p.ParameterGroup pg')
					->where( 'pg.id = ?', $this->id )
					->orderBy('p.pri')
					->execute();
	}


}