<?php

/**
 * ParameterPicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ParameterPicture extends BaseParameterPicture
{
	public function getEditForm()
	{

		if( $this->editForm == null )
			$this->editForm = new ParameterPictureForm( $this );
			
		return $this->editForm;
	}
	
	
  public function createAndGetParamValueForm(  $product = null ){
  	
  	  	$this->setParamValueForm( new ParameterProductValuePictureForm( 
  					Doctrine::getTable('ParameterProductValue')
  						->getObjectForProductAndParameter( $product, $this ) ) );
  						
	  	return $this->getParamValueForm();

  }
}