<?php

/**
 * Parameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Parameter extends BaseParameter
{
	
	public $editForm = null;
	public $paramForm = null;
	
	
	public function getSameLevelNodes(){
		return Doctrine::getTable('Parameter')->findByGroupId( $this->getGroupId() );
	}
	
	
	public function getEditForm(){

		if( $this->editForm == null )
			$this->editForm = new ParameterForm( $this );
			
		return $this->editForm;
	}
	
	
	public function getParamValueForm(){
		return $this->paramForm;
	}
	
	
	public function setParamValueForm( $paramForm ){
		$this->paramForm =  $paramForm;
	}
	
	
  public function createAndGetParamValueForm( $product ){
  	

  	$this->setParamValueForm( new ParameterProductValueForm( 
  					Doctrine::getTable('ParameterProductValue')
  						->getObjectForProductAndParameter( $product, $this ) ) );
  						
  	 return $this->getParamValueForm();
  	
  }
	
  
}