<?php

/**
 * Placeholder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Placeholder extends BasePlaceholder
{
	public function getModules(){
		echo "BIG BIG ERROR";
		exit;
		//return Doctrine::getTable('Module')->getOrderedModulesOf( $this->id );
	}
	
	public function getSameLevelNodes()
	{
		$result = array();
		foreach( Doctrine::getTable('Placeholder')->findByStructureId( $this->structure_id ) as $p )
			if( $p->name == $this->name )
				$result[] = $p;
		return $result;
	}
	
	
	public function postSave( $obj )
	{
		$this->setDefaultPriority();
		
	}
	
	
	public function setDefaultPriority()
	{
		if( $this->pri === 0 )
		{
			$this->pri = $this->id;
			$this->save();
		}
	}

}