<?php

/**
 * ShippingZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ShippingZone extends BaseShippingZone
{
	
	/* used in backend LIST action */
	public function getCulturedName(){
		$context = sfContext::getInstance();
		
		return $this->Translation[$context->getUser()->getCulture()]
					->name;
		
	}
	
	
	public function getIntervals(){
		return $this->getTable()->createQuery('intervals')
			->select('i.*')
			->from('ShippingZoneInterval i')
			->innerJoin('i.ShippingZone z WITH z.id = ?', $this->getId())
			->orderBy('i.start asc')
			->execute();
	}

}