PublicUser:
    columns:
        name: { type: string(255), notnull: true }
        email: { type: string(255), notnull: true }
        currency: { type: string(255), notnull: false }
        login: { type: string(255), notnull: true, unique: true }
        password: { type: string(255), notnull: true }
        address1: { type: string(255), notnull: false }
        address2: { type: string(255), notnull: false }
        city: { type: string(255), notnull: false }
        state: { type: string(255), notnull: false }
        country: { type: string(255), notnull: false }
        zip: { type: string(255), notnull: false }
    
PublicUserAddresses:
    columns:
        public_user_id: { type: integer, notnull: false }
        title: { type: string(255), notnull: true, default: "new address" }
        name: { type: string(255), notnull: true }
        address: { type: string(255), notnull: true }
        city: { type: string(255), notnull: false }
        state: { type: string(255), notnull: false }
        country: { type: string(255), notnull: false }
        zip: { type: string(255), notnull: false }
    relations:
        PublicUser:
            local: public_user_id
            foreign: id
            foreignAlias: Addresses
            onDelete: CASCADE
            onUpdate: CASCADE

        