generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TransUnit
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          trans_unit
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          display: [source]
      filter: 
          display: [cat_id]
      form:    ~
      edit:    ~
      new:     ~
